# Generated by Django 4.2.1 on 2023-05-16 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(db_column='email address', max_length=254, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('full_name', models.CharField(db_column='full name', max_length=150)),
                ('billing_address', models.CharField(db_column='billing address', max_length=250)),
                ('default_shipping_address', models.CharField(db_column='default shipping address', max_length=250)),
                ('country', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
